language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r s-with-me *
  - mkdir -p deploy
  - mv s-with-me.zip deploy/s-with-me.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: swithme-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: swithme-build
    key: s-with-me.zip
    build_type: zip
    application: s-with-me
    deployment_group: s-with-me-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - urazer0@ajou.ac.kr
      - youngsangsid@ajou.ac.kr
      - wjdthgmlek@ajou.ac.kr
      - marblegiraffe@ajou.ac.kr
